### PR TITLE
Vagrant & Chef setup

### LINKED ISSUE #10: Create VM for local development
## Problem
We need to develop locally on this project, and we want everyone to maintain consistent versions of software packages. 

## Solution
Create a VM using Vagrant and Chef to manage the dependencies. Include:
- Postgres
- Ruby

See example at https://gorails.com/guides/using-vagrant-for-rails-development

### PR DESCRIPTION
**Pull request by isometimescode**
closes #10 

Right now we don't seem to need anything besides Ruby and Postgresql, so that's all this VM has.

QA by checking out this feature branch `vagrant-10`, then reading the installation steps in the [wiki](https://github.com/WomenWhoCode/fluffy-spork/wiki/General-Setup-Guide) and try it locally. Since we don't actually have any project code to test yet, I just added a simple Gemfile with the `pg` gem and a test script to connect to the db. I can delete the test file before merging back to `staging`.

### CODE REVIEW

**Comment by zassmin** [comment]
image

ran into ^^^ do we have an id for a target machine or do I create a new env?

**Comment by isometimescode** [comment]
@zassmin It looks like you need to checkout the `vagrant-10` branch first; I should have mentioned that in the QA steps sorry :koala:

**Comment by zassmin** [comment]
haha, so silly of me, of course

**Comment by zassmin** [comment]
image
Should we add this to gitignore ^^^?

**Comment by zassmin** [comment]
last thing, was trying to test with the vagrant console by bundling and got: 

image

I do see the gemfile is in branch... 🤔

**Comment by isometimescode** [comment]
> Should we add this to gitignore ^^^?

Good catch, I have `.vagrant` ignored globally so it didn't come up for me. Adding now!

And as for the other one, it looks like you are in the home directory. All the files are in `/vagrant/` by default, however, we can sync them to the home directory instead?

**Comment by zassmin** [comment]
@isometimescode  I clearly wasn't reading the wiki 🙈

**Pull request merged**
